#!/usr/bin/env python3
"""Build a prioritized hard-case queue from extraction events.

Input: NDJSON events generated by TREX (`--event-log`)
Output: NDJSON queue items sorted by priority descending
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


FEEDBACK_WEIGHTS: dict[str, float] = {
    "missing_table": 6.0,
    "broken_table": 5.0,
    "wrong_columns": 4.0,
    "wrong_rows": 4.0,
    "bad_extract": 4.0,
    "empty_output": 5.0,
}


@dataclass
class Aggregate:
    tenant_id: str
    document_key: str
    page: int | None
    attempts: int = 0
    priority: float = 0.0
    reasons: set[str] = field(default_factory=set)
    last_status: str | None = None
    last_error_code: str | None = None
    last_requested_mode: str | None = None
    last_seen_ms: int = 0
    latest_table_count: int | None = None
    latest_quality_score: float | None = None
    training_opt_in: bool = False


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build hard-case queue from extraction events")
    parser.add_argument("--events", required=True, help="Input event NDJSON path")
    parser.add_argument("--output", required=True, help="Output hard-case NDJSON path")
    parser.add_argument("--min-priority", type=float, default=6.0)
    parser.add_argument("--limit", type=int, default=1000)
    parser.add_argument("--quality-threshold", type=float, default=0.12)
    parser.add_argument("--min-non-empty-cells", type=int, default=4)
    parser.add_argument(
        "--include-non-opt-in",
        action="store_true",
        help="Include events where training_opt_in=false",
    )
    return parser.parse_args()


def read_ndjson(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    if not path.exists():
        return rows

    with path.open("r", encoding="utf-8") as file:
        for line_no, line in enumerate(file, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                parsed = json.loads(line)
            except json.JSONDecodeError:
                continue
            if isinstance(parsed, dict):
                parsed["_line_no"] = line_no
                rows.append(parsed)
    return rows


def event_pages(event: dict[str, Any]) -> list[dict[str, Any]]:
    pages = event.get("page_metrics")
    if isinstance(pages, list) and pages:
        normalized: list[dict[str, Any]] = []
        for item in pages:
            if not isinstance(item, dict):
                continue
            normalized.append(
                {
                    "page": item.get("page"),
                    "table_count": item.get("table_count"),
                    "non_empty_cells": item.get("non_empty_cells"),
                    "quality_score": item.get("mean_density"),
                }
            )
        if normalized:
            return normalized

    return [
        {
            "page": None,
            "table_count": event.get("table_count"),
            "non_empty_cells": None,
            "quality_score": event.get("quality_score"),
        }
    ]


def score_signal(
    event: dict[str, Any],
    page_info: dict[str, Any],
    quality_threshold: float,
    min_non_empty_cells: int,
) -> tuple[float, set[str]]:
    score = 0.0
    reasons: set[str] = set()

    status = event.get("status")
    if status == "error":
        score += 8.0
        error_code = event.get("error_code") or "unknown"
        reasons.add(f"error:{error_code}")

    table_count = page_info.get("table_count")
    if isinstance(table_count, int):
        if table_count == 0:
            score += 4.0
            reasons.add("zero_table")
        elif table_count >= 20:
            score += 2.0
            reasons.add("possible_over_split")

    quality = page_info.get("quality_score")
    if isinstance(quality, (int, float)) and quality < quality_threshold:
        score += 2.0
        reasons.add("low_quality")

    non_empty_cells = page_info.get("non_empty_cells")
    if isinstance(non_empty_cells, int) and non_empty_cells <= min_non_empty_cells:
        score += 2.0
        reasons.add("sparse_cells")

    feedback_tag = event.get("feedback_tag")
    if isinstance(feedback_tag, str) and feedback_tag:
        score += FEEDBACK_WEIGHTS.get(feedback_tag, 1.0)
        reasons.add(f"feedback:{feedback_tag}")

    requested_mode = event.get("requested_mode")
    if requested_mode in ("auto", "dl") and table_count == 0:
        score += 1.5
        reasons.add("auto_mode_miss")

    return score, reasons


def aggregate_events(args: argparse.Namespace, events: list[dict[str, Any]]) -> list[Aggregate]:
    aggregated: dict[tuple[str, str, int | None], Aggregate] = {}

    for event in events:
        training_opt_in = bool(event.get("training_opt_in", False))
        if not training_opt_in and not args.include_non_opt_in:
            continue

        tenant_id = str(event.get("tenant_id") or "default")
        document_key = str(event.get("document_key") or "unknown")

        for page_info in event_pages(event):
            page = page_info.get("page")
            page = page if isinstance(page, int) and page >= 1 else None

            key = (tenant_id, document_key, page)
            item = aggregated.get(key)
            if item is None:
                item = Aggregate(
                    tenant_id=tenant_id,
                    document_key=document_key,
                    page=page,
                )
                aggregated[key] = item

            signal_score, signal_reasons = score_signal(
                event,
                page_info,
                quality_threshold=args.quality_threshold,
                min_non_empty_cells=args.min_non_empty_cells,
            )

            item.attempts += 1
            item.priority += signal_score
            item.reasons.update(signal_reasons)
            item.last_status = event.get("status")
            item.last_error_code = event.get("error_code")
            item.last_requested_mode = event.get("requested_mode")
            item.last_seen_ms = max(item.last_seen_ms, int(event.get("ts_unix_ms") or 0))
            table_count = page_info.get("table_count")
            if isinstance(table_count, int):
                item.latest_table_count = table_count
            quality = page_info.get("quality_score")
            if isinstance(quality, (int, float)):
                item.latest_quality_score = float(quality)
            item.training_opt_in = training_opt_in

    for item in aggregated.values():
        item.priority += min(item.attempts, 6) * 0.6

    rows = [item for item in aggregated.values() if item.priority >= args.min_priority]
    rows.sort(key=lambda item: (item.priority, item.attempts, item.last_seen_ms), reverse=True)
    return rows[: args.limit]


def write_ndjson(path: Path, rows: list[Aggregate]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as file:
        for row in rows:
            payload = {
                "tenant_id": row.tenant_id,
                "document_key": row.document_key,
                "page": row.page,
                "priority": round(row.priority, 4),
                "attempts": row.attempts,
                "reasons": sorted(row.reasons),
                "last_status": row.last_status,
                "last_error_code": row.last_error_code,
                "last_requested_mode": row.last_requested_mode,
                "last_seen_ms": row.last_seen_ms,
                "latest_table_count": row.latest_table_count,
                "latest_quality_score": row.latest_quality_score,
                "training_opt_in": row.training_opt_in,
            }
            file.write(json.dumps(payload, ensure_ascii=False) + "\n")


def main() -> None:
    args = parse_args()
    events = read_ndjson(Path(args.events))
    queue = aggregate_events(args, events)
    write_ndjson(Path(args.output), queue)

    print(
        json.dumps(
            {
                "input_events": len(events),
                "queue_items": len(queue),
                "output": args.output,
            },
            ensure_ascii=False,
        )
    )


if __name__ == "__main__":
    main()
