/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum ParseModeOption {
  Auto = 'Auto',
  Lattice = 'Lattice',
  Stream = 'Stream',
  Dl = 'Dl'
}
export const enum DlFallbackOption {
  Auto = 'Auto',
  Lattice = 'Lattice',
  Stream = 'Stream'
}
export interface ExtractOptions {
  pages?: Array<number>
  mode?: ParseModeOption
  dlModel?: string
  dlMinConfidence?: number
  dlFallback?: DlFallbackOption
}
export interface Table {
  page: number
  tableIndex: number
  headers: Array<string>
  rows: Array<Array<string>>
}
export declare function extract(pdfPath: string, options?: ExtractOptions | undefined | null): Array<Table>
export declare function extractCsv(pdfPath: string, options?: ExtractOptions | undefined | null): string
export declare function extractFromBuffer(pdfBuffer: Buffer, options?: ExtractOptions | undefined | null): Array<Table>
export declare function extractCsvFromBuffer(pdfBuffer: Buffer, options?: ExtractOptions | undefined | null): string
